export default {
    SEND_MESSAGE: 'SEND_MESSAGE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    HISTORY_MESSAGE: 'HISTORY_MESSAGE',
    SEARCH_MESSAGE: 'SEARCH_MESSAGE',
    SEND_UPDATED_MESSAGE: 'SEND_UPDATED_MESSAGE',
    GET_UPDATED_MESSAGE: 'GET_UPDATED_MESSAGE',
    SAVE_FILE_MESSAGE: 'SAVE_FILE_MESSAGE',
    CANCEL_UPDATING_MESSAGE: 'CANCEL_UPDATING_MESSAGE'
};
