export default {
    START_RECORD: 'START_RECORD',
    STOP_RECORD: 'STOP_RECORD',
    REMOVE_RECORD: 'REMOVE_RECORD',
    SEND_RECORD: 'SEND_RECORD',
    DEST_PEERS_VIDEOMESSAGE: 'DEST_PEERS_VIDEOMESSAGE'
};
